# Generated by Django 2.1 on 2019-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_userssummaryreport_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_name', models.CharField(max_length=100)),
                ('group_leader', models.ManyToManyField(related_name='group_leader', to='reports.UsersList')),
                ('member', models.ManyToManyField(related_name='group_member', to='reports.UsersList')),
            ],
        ),
    ]
